/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Estimate */
        post: operations["create_estimate_api_v1_estimate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estimate/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Estimate Options */
        get: operations["get_estimate_options_api_v1_estimate_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Rates */
        get: operations["read_rates_api_v1_rates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CategoryBreakdown */
        CategoryBreakdown: {
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Cost Pkr */
            cost_pkr: number;
            /** Percentage */
            percentage: number;
            /** Materials */
            materials?: components["schemas"]["MaterialLineItem"][];
        };
        /**
         * City
         * @enum {string}
         */
        City: "islamabad" | "rawalpindi";
        /** EstimateOptions */
        EstimateOptions: {
            /** Plot Sizes */
            plot_sizes: components["schemas"]["PlotSize"][];
            /** Cities */
            cities: components["schemas"]["City"][];
            /** Storeys */
            storeys: components["schemas"]["Storeys"][];
            /** Quality Grades */
            quality_grades: components["schemas"]["QualityGrade"][];
        };
        /** EstimateRequest */
        EstimateRequest: {
            plot_size: components["schemas"]["PlotSize"];
            city: components["schemas"]["City"];
            storeys: components["schemas"]["Storeys"];
            quality_grade: components["schemas"]["QualityGrade"];
        };
        /** EstimateResponse */
        EstimateResponse: {
            plot_size: components["schemas"]["PlotSize"];
            city: components["schemas"]["City"];
            storeys: components["schemas"]["Storeys"];
            quality_grade: components["schemas"]["QualityGrade"];
            /** Built Up Area Sqft */
            built_up_area_sqft: number;
            /** Total Cost Low Pkr */
            total_cost_low_pkr: number;
            /** Total Cost High Pkr */
            total_cost_high_pkr: number;
            /** Categories */
            categories: components["schemas"]["CategoryBreakdown"][];
            /**
             * Disclaimer
             * @default Preliminary estimate only, not a binding quotation. Bylaw and material quantity ratios are placeholder values pending civil engineer review.
             */
            disclaimer: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MaterialLineItem */
        MaterialLineItem: {
            /** Material */
            material: string;
            /** Unit */
            unit: string;
            /** Quantity */
            quantity: number;
            /** Rate Pkr */
            rate_pkr: number;
            /** Cost Pkr */
            cost_pkr: number;
        };
        /** MaterialRate */
        MaterialRate: {
            /** Material */
            material: string;
            /** Label */
            label: string;
            /** Unit */
            unit: string;
            /** Rate Pkr */
            rate_pkr: number;
            /**
             * Trend Direction
             * @enum {string}
             */
            trend_direction: "up" | "down" | "flat";
            /** Trend Pct */
            trend_pct: number;
            /** History */
            history: components["schemas"]["RateHistoryPoint"][];
        };
        /**
         * PlotSize
         * @enum {string}
         */
        PlotSize: "3_marla" | "5_marla" | "7_marla" | "10_marla" | "1_kanal" | "2_kanal";
        /**
         * QualityGrade
         * @enum {string}
         */
        QualityGrade: "economy" | "standard" | "premium";
        /** RateHistoryPoint */
        RateHistoryPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Rate Pkr */
            rate_pkr: number;
        };
        /** RatesResponse */
        RatesResponse: {
            city: components["schemas"]["City"];
            /** Rates */
            rates: components["schemas"]["MaterialRate"][];
            /**
             * Disclaimer
             * @default Placeholder seed rates and fabricated trend history — not yet backed by the live Daily Material Rates admin data.
             */
            disclaimer: string;
        };
        /**
         * Storeys
         * @enum {number}
         */
        Storeys: 1 | 1.5 | 2 | 2.5 | 3;
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_estimate_api_v1_estimate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstimateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_estimate_options_api_v1_estimate_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateOptions"];
                };
            };
        };
    };
    read_rates_api_v1_rates_get: {
        parameters: {
            query?: {
                city?: components["schemas"]["City"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
