/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Estimate */
        post: operations["create_estimate_api_v1_estimate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estimate/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Estimate Options */
        get: operations["get_estimate_options_api_v1_estimate_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Rates */
        get: operations["read_rates_api_v1_rates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/renovation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Renovation Estimate */
        post: operations["create_renovation_estimate_api_v1_renovation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/renovation/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Renovation Options */
        get: operations["get_renovation_options_api_v1_renovation_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Current User */
        get: operations["read_current_user_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-estimates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Saved Estimates */
        get: operations["list_saved_estimates_api_v1_saved_estimates_get"];
        put?: never;
        /** Create Saved Estimate */
        post: operations["create_saved_estimate_api_v1_saved_estimates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-estimates/{estimate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Saved Estimate */
        get: operations["read_saved_estimate_api_v1_saved_estimates__estimate_id__get"];
        put?: never;
        post?: never;
        /** Delete Saved Estimate */
        delete: operations["delete_saved_estimate_api_v1_saved_estimates__estimate_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Download Report */
        post: operations["download_report_api_v1_reports_pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/saved-estimates/{estimate_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Saved Estimate Report */
        get: operations["download_saved_estimate_report_api_v1_reports_saved_estimates__estimate_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CategoryBreakdown */
        CategoryBreakdown: {
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Cost Pkr */
            cost_pkr: number;
            /** Percentage */
            percentage: number;
            /** Materials */
            materials?: components["schemas"]["MaterialLineItem"][];
        };
        /**
         * City
         * @enum {string}
         */
        City: "islamabad" | "rawalpindi";
        /** EstimateOptions */
        EstimateOptions: {
            /** Plot Sizes */
            plot_sizes: components["schemas"]["PlotSize"][];
            /** Cities */
            cities: components["schemas"]["City"][];
            /** Storeys */
            storeys: components["schemas"]["Storeys"][];
            /** Quality Grades */
            quality_grades: components["schemas"]["QualityGrade"][];
        };
        /** EstimateRequest */
        EstimateRequest: {
            plot_size: components["schemas"]["PlotSize"];
            city: components["schemas"]["City"];
            storeys: components["schemas"]["Storeys"];
            quality_grade: components["schemas"]["QualityGrade"];
        };
        /** EstimateResponse */
        EstimateResponse: {
            plot_size: components["schemas"]["PlotSize"];
            city: components["schemas"]["City"];
            storeys: components["schemas"]["Storeys"];
            quality_grade: components["schemas"]["QualityGrade"];
            /** Built Up Area Sqft */
            built_up_area_sqft: number;
            /** Total Cost Low Pkr */
            total_cost_low_pkr: number;
            /** Total Cost High Pkr */
            total_cost_high_pkr: number;
            /** Categories */
            categories: components["schemas"]["CategoryBreakdown"][];
            /**
             * Disclaimer
             * @default Preliminary estimate only, not a binding quotation. Material rates are sourced estimates (updated 2026-09-25), not a live feed. Bylaw coverage ratios and material quantity ratios are still unverified, pending a civil engineer's review.
             */
            disclaimer: string;
        };
        /**
         * EstimateType
         * @enum {string}
         */
        EstimateType: "house" | "renovation";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MaterialLineItem */
        MaterialLineItem: {
            /** Material */
            material: string;
            /** Unit */
            unit: string;
            /** Quantity */
            quantity: number;
            /** Rate Pkr */
            rate_pkr: number;
            /** Cost Pkr */
            cost_pkr: number;
        };
        /** MaterialRate */
        MaterialRate: {
            /** Material */
            material: string;
            /** Label */
            label: string;
            /** Unit */
            unit: string;
            /** Rate Pkr */
            rate_pkr: number;
            /**
             * Trend Direction
             * @enum {string}
             */
            trend_direction: "up" | "down" | "flat";
            /** Trend Pct */
            trend_pct: number;
            /** History */
            history: components["schemas"]["RateHistoryPoint"][];
        };
        /**
         * PlotSize
         * @enum {string}
         */
        PlotSize: "3_marla" | "5_marla" | "7_marla" | "10_marla" | "1_kanal" | "2_kanal";
        /**
         * QualityGrade
         * @enum {string}
         */
        QualityGrade: "economy" | "standard" | "premium";
        /** RateHistoryPoint */
        RateHistoryPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Rate Pkr */
            rate_pkr: number;
        };
        /** RatesResponse */
        RatesResponse: {
            city: components["schemas"]["City"];
            /** Rates */
            rates: components["schemas"]["MaterialRate"][];
            /**
             * Disclaimer
             * @default Today's rate is a sourced estimate (updated 2026-09-25), not a live feed. The 14-day trend and history shown are still fabricated for demonstration — not yet backed by real historical data or the Daily Material Rates admin tool.
             */
            disclaimer: string;
        };
        /** RenovationOptions */
        RenovationOptions: {
            /** Work Items */
            work_items: components["schemas"]["RenovationWorkItem"][];
            /** Cities */
            cities: components["schemas"]["City"][];
            /** Quality Grades */
            quality_grades: components["schemas"]["QualityGrade"][];
        };
        /** RenovationRequest */
        RenovationRequest: {
            /** Length Ft */
            length_ft: number;
            /** Width Ft */
            width_ft: number;
            /**
             * Height Ft
             * @default 9
             */
            height_ft: number;
            /** Work Items */
            work_items: components["schemas"]["RenovationWorkItem"][];
            city: components["schemas"]["City"];
            quality_grade: components["schemas"]["QualityGrade"];
        };
        /** RenovationResponse */
        RenovationResponse: {
            /** Floor Area Sqft */
            floor_area_sqft: number;
            /** Wall Area Sqft */
            wall_area_sqft: number;
            /** Items */
            items: components["schemas"]["CategoryBreakdown"][];
            /** Total Cost Low Pkr */
            total_cost_low_pkr: number;
            /** Total Cost High Pkr */
            total_cost_high_pkr: number;
            /**
             * Disclaimer
             * @default Preliminary estimate only, not a binding quotation. Material rates are sourced estimates (updated 2026-09-25); tile adhesive rate, material quantity ratios, labour benchmarks and the door/window wall-area deduction are still unverified.
             */
            disclaimer: string;
        };
        /**
         * RenovationWorkItem
         * @enum {string}
         */
        RenovationWorkItem: "floor_tiling" | "wall_tiling" | "painting" | "plastering";
        /** ReportRequest */
        ReportRequest: {
            estimate_type: components["schemas"]["EstimateType"];
            /** Label */
            label?: string | null;
            /** Request Data */
            request_data: {
                [key: string]: unknown;
            };
            /** Response Data */
            response_data: {
                [key: string]: unknown;
            };
        };
        /** SavedEstimateCreate */
        SavedEstimateCreate: {
            estimate_type: components["schemas"]["EstimateType"];
            /** Label */
            label: string;
            /** Request Data */
            request_data: {
                [key: string]: unknown;
            };
            /** Response Data */
            response_data: {
                [key: string]: unknown;
            };
        };
        /** SavedEstimateRead */
        SavedEstimateRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            estimate_type: components["schemas"]["EstimateType"];
            /** Label */
            label: string;
            /** Request Data */
            request_data: {
                [key: string]: unknown;
            };
            /** Response Data */
            response_data: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SavedEstimateSummary
         * @description Lighter shape for list views — omits the full request/response payloads.
         */
        SavedEstimateSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            estimate_type: components["schemas"]["EstimateType"];
            /** Label */
            label: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * Storeys
         * @enum {number}
         */
        Storeys: 1 | 1.5 | 2 | 2.5 | 3;
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserRead"];
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["UserRole"];
        };
        /** UserLogin */
        UserLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "owner" | "contractor";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_estimate_api_v1_estimate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstimateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_estimate_options_api_v1_estimate_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateOptions"];
                };
            };
        };
    };
    read_rates_api_v1_rates_get: {
        parameters: {
            query?: {
                city?: components["schemas"]["City"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_renovation_estimate_api_v1_renovation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenovationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenovationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_renovation_options_api_v1_renovation_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenovationOptions"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_current_user_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    list_saved_estimates_api_v1_saved_estimates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedEstimateSummary"][];
                };
            };
        };
    };
    create_saved_estimate_api_v1_saved_estimates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedEstimateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedEstimateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_saved_estimate_api_v1_saved_estimates__estimate_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                estimate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedEstimateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_saved_estimate_api_v1_saved_estimates__estimate_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                estimate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_report_api_v1_reports_pdf_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_saved_estimate_report_api_v1_reports_saved_estimates__estimate_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                estimate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
