"""add site diary entries

Revision ID: cbd4324101b9
Revises: 7ee686ae41b8
Create Date: 2026-09-25 00:23:57.175564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd4324101b9'
down_revision: Union[str, Sequence[str], None] = '7ee686ae41b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_diary_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('saved_estimate_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('photo_data', sa.LargeBinary(), nullable=True),
    sa.Column('photo_content_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['saved_estimate_id'], ['saved_estimates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_diary_entries_saved_estimate_id'), 'site_diary_entries', ['saved_estimate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_diary_entries_saved_estimate_id'), table_name='site_diary_entries')
    op.drop_table('site_diary_entries')
    # ### end Alembic commands ###
